apiVersion: apps/v1
kind: Deployment
metadata:
  name: oneinfra-console
  namespace: oneinfra-system
spec:
  template:
    spec:
      containers:
      - name: console
        args:
        - serve
        - --auth=github-oauth
        env:
        - name: GITHUB_OAUTH2_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: github-oauth
              key: client-id
        - name: GITHUB_OAUTH2_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: github-oauth
              key: client-secret
