apiVersion: v1
kind: Namespace
metadata:
  name: oneinfra-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: oneinfra-users
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-user
  namespace: oneinfra-users
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: create-namespaces
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-user
  namespace: oneinfra-users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: read-user
subjects:
- kind: ServiceAccount
  name: default
  namespace: oneinfra-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: create-namespaces
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: create-namespaces
subjects:
- kind: ServiceAccount
  name: default
  namespace: oneinfra-system
---
apiVersion: v1
data:
  password: JDJhJDEwJGhXSGtnZEFMWXQuRGYvT2pTOVNnQmVzc2R2dWZWZC5XbVdac1lodDZwWHBYVkh4dU11bXE2Cg==
kind: Secret
metadata:
  name: sample-user
  namespace: oneinfra-users
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: oneinfra-console
  name: oneinfra-console
  namespace: oneinfra-system
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    control-plane: oneinfra-console
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: oneinfra-console
  name: oneinfra-console
  namespace: oneinfra-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: oneinfra-console
  template:
    metadata:
      labels:
        control-plane: oneinfra-console
    spec:
      containers:
      - args:
        - serve
        - --auth=kubernetes-secrets
        env:
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              key: jwt-key
              name: jwt-key
        image: oneinfra/console:20.05.0-alpha1
        name: console
        ports:
        - containerPort: 9000
