apiVersion: v1
kind: Namespace
metadata:
  name: oneinfra-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: create-namespaces
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: create-namespaces
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: create-namespaces
subjects:
- kind: ServiceAccount
  name: default
  namespace: oneinfra-system
---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: oneinfra-console
  name: oneinfra-console
  namespace: oneinfra-system
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    control-plane: oneinfra-console
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: oneinfra-console
  name: oneinfra-console
  namespace: oneinfra-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: oneinfra-console
  template:
    metadata:
      labels:
        control-plane: oneinfra-console
    spec:
      containers:
      - args:
        - serve
        - --auth=github-oauth
        env:
        - name: GITHUB_OAUTH2_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: client-id
              name: github-oauth
        - name: GITHUB_OAUTH2_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: client-secret
              name: github-oauth
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              key: jwt-key
              name: jwt-key
        image: oneinfra/console:20.05.0-alpha2
        name: console
        ports:
        - containerPort: 9000
