apiVersion: apps/v1
kind: Deployment
metadata:
  name: oneinfra-console
  namespace: oneinfra-system
spec:
  template:
    spec:
      containers:
      - name: console
        args:
        - serve
        - --auth=kubernetes-secrets
