---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-user
  namespace: oneinfra-users
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-user
  namespace: oneinfra-users
subjects:
- kind: ServiceAccount
  name: default
  namespace: oneinfra-system
roleRef:
  kind: Role
  name: read-user
  apiGroup: rbac.authorization.k8s.io
