---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: create-namespaces
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: create-namespaces
subjects:
- kind: ServiceAccount
  name: default
  namespace: oneinfra-system
roleRef:
  kind: ClusterRole
  name: create-namespaces
  apiGroup: rbac.authorization.k8s.io
