apiVersion: v1
kind: Service
metadata:
  name: oneinfra-console
  labels:
    control-plane: oneinfra-console
spec:
  ports:
    - port: 80
      targetPort: 9000
      protocol: TCP
  selector:
    control-plane: oneinfra-console
